version: '3.8'

services:
  x-python-containers: &python-containers
    build: .
    volumes:
      - .:/app
    env_file:
      - .env.dev

  web:
    <<: *python-containers
    command: gunicorn sibdev_job.wsgi --bind 0.0.0.0:8000
    ports:
      - 8000:8000
    depends_on:
      - db
      - redis

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env.dev

  redis:
    image: redis:7

  autotests:
    <<: *python-containers
    command: python manage.py test
    depends_on:
      - db

volumes:
  postgres_data: