# Generated by Django 4.2.3 on 2023-07-06 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0002_rename_gem_deal_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='deals.customer'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='deals.gem'),
        ),
    ]
