# Generated by Django 4.2.3 on 2023-07-06 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0003_alter_deal_customer_alter_deal_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='gems',
            field=models.ManyToManyField(related_name='customers', through='deals.Deal', to='deals.gem'),
        ),
    ]
